### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by jancborchardt** [tube42/drumon#14]
Here’s a quick proposal for a new app icon based on the interface of the app itself. That way when you read the name and know a tiny bit about drum machine interfaces, you know exactly what to expect.
(As in: Is it one of these strange photographed drumsets where you can tap on the toms and cymbals, or is it a sequencer?)

![drum-on multiple](https://user-images.githubusercontent.com/925062/50401735-2130a800-0791-11e9-8e63-b5fc3f59e90a.png)
Source SVG at https://cloud.jancborchardt.net/index.php/s/YsZHCRgoCQcbBME

(For the record, I think @anaufalm’s logo proposal at https://github.com/tube42/drumon/issues/6#issuecomment-408194959 is really great. Good combination of the "d" and "o" for Drum On, and the drum itself. I’d only change the typeface.)

Let me know what you think @tube42. :)

**Comment by jancborchardt** [comment]
Here with possible text, using [Montserrat Bold](https://github.com/JulietaUla/Montserrat):

![drum-on-logo](https://user-images.githubusercontent.com/925062/50401941-b4b6a880-0792-11e9-8b68-ac8203eb8f2d.png)

**Comment by tube42** [comment]
I like how it looks like the pads in the app. The problem is that to someone who has not used the app this doesn't say anything. Is it a game? Is this a dice?

If you are into icons design, I think the ones inside the app are in a more urgent need of a face lift ;)

**Comment by jancborchardt** [comment]
The target audience is musicians, and many musicians know sequencers. ;) Together with the name and the description it makes it better understandable.

It's definitely more understandable than the current icon, which is just a repeat of the name, and also males it look as if it's one of those apps where it's a drumset photographed and you can tap the different parts – that's what I thought.

For the icons in the app I can recommend checking for icons on https://thenounproject.com

**Comment by tube42** [comment]
Using the colors from the classic Akai machines, I get this. Not sure if it is an improvement

![new_icon](https://user-images.githubusercontent.com/1971317/50443098-0c275680-0902-11e9-9b5a-83d95dd5337d.png)

**Comment by jancborchardt** [comment]
Hmm, it looks more complex, and less like your app. So it doesn’t work that well as a logo I’d say.

If you’re not happy with either the logo by @anaufalm’s or me, I suggest submitting a job to the [Open Source Design job board](https://opensourcedesign.net/jobs/). :slightly_smiling_face:

**Comment by tube42** [comment]
After some experimenting I came up with this one:

![ic_launcher](https://user-images.githubusercontent.com/1971317/50453481-22083c00-0941-11e9-89ce-03a216239487.png)

This will be used in version 0.2.9.
