### ISSUE TITLE
Set initial beat?

### ISSUE THREAD

**Issue by SmilingHorse** [tube42/drumon#15]
Choosing the first beat to start off from would be useful for the flamenco clock.

A video explaining it and giving examples: https://www.youtube.com/watch?v=DGJDiJ94-GA

A web app doing something similar: http://acompas.org

So, you'd pick the 3/4 for a 12 beat, setup the claps and sticks, and then switch palos by choosing the different initial beat and adjust the tempo. For example, say you have:

00x
00x
0x0
x0x

You'd be able to tap a button and then hit the 1st beat and get Solea and so on...
Or the 12th beat and get Bulerias and so on...
Or the 8th and get Siguiriyas and so on...

It can also be done with two buttons that shift the pattern cyclically one beat back and forth or maybe some kind of slider that shifts the whole pattern per total beats. Like, the slider would have 12 steps with the first being starting off with the first beat and the 3rd the 3rd... I suppose it could also visually rotate the whole pattern as cool effect of sorts?

Well, just a cool thing to have really to save some time.

**Comment by tube42** [comment]
Thanks for the idea! I am learning Spanish guitar myself and this function would have been a good thing to have.

... but I don't think it works here since the app doesn't really have a notion of start/stop for beats & measures. Notice that the pause/play button doesn't reset the position. Unless I can come up with a really cool solution that doesn't clutter the UI with new buttons I have to drop this idea.

**Comment by SmilingHorse** [comment]
> Unless I can come up with a really cool solution that doesn't clutter the UI with new buttons I have to drop this idea.

@tube42 Makes sense. Maybe a gesture would work? Horizontal/Vertical slide to shift the beat. Like how VLC has vertical for volume and horizontal for time? Just a thought.

Either way, thanks and back to the rasgueos :)

**Comment by tube42** [comment]
A gesture would work, but it would also work for people who do it accidentally ;)
