### ISSUE TITLE
Add the "Load Sound" and "Edit Sound" Features in Drum On!

### ISSUE THREAD

**Issue by ahyar92** [tube42/drumon#18]
![2.png](https://cdn.steemitimages.com/DQmaEwMmBiS6y5gyW4Q3cPdUdWPW4bXGu2WHhAekgniL8Ha/2.png)

![1.png](https://cdn.steemitimages.com/DQmWftXXzg6RxXTGcb3JZdET53Z3mTnmox21wJvEkFJDaym/1.png)

### Components
The components (Features) I want to suggest is:

<table>
<thead>
<tr><th>Feature Name</th><th>Points</th>
</thead>
<tbody>
<tr><td> Load Sound</td><td>Load Song and Lessons</td>
<tr><td> Edit Sound</td><td>Play, Crop, Reset, Fade in and Fade Out, Export To Wav, Edit Title, and Save Project</td>
</table>

![1.png](https://cdn.steemitimages.com/DQmWftXXzg6RxXTGcb3JZdET53Z3mTnmox21wJvEkFJDaym/1.png)

### Proposal Description
[Drum On!](https://github.com/tube42/drumon) is a very interesting project. This really helps users who want to make an Instrumental beat for Drums. The world is increasingly modern, you can control musical instruments through your smartphone. Drum On! also included in the latest innovations.

In my opinion, Drum On! has provided interesting features even though it's still a little simple. Its use is very easy, you can understand how to use it easily after using it for a few minutes. Although this is quite interesting, there are still things that are lacking! developers must think about further development in order to compete with similar applications. 

Developers don't just have to think about competition, but developers also have to think about user satisfaction and also have to be able to improve user experience. Need to add more interesting features to make Drum On! become more cool and interesting later. Therefore, I would like to suggest some additional features for the Drum On!, I want to Drum On! keep innovating to be more attractive. 

#### Load Song
I hope the developer must pay attention to the first feature that I recommend this. This is an important feature, this is useful for users who want to collaborate or combine music/songs with the beat of Drum from Drum On!. 

By being able to combine music / songs with the beat of Drum, this is certainly more synchronous with the tempo. And also users can combine with other Intrumental like piano or guitar to produce perfect music later.

#### Lessons
This is an additional feature that I would like to suggest to add to the "Load Sound" page. This is useful for displaying tutorials or lessons for drum beats. It will certainly be an inspiration in creating future Instrumental Drums by users.

I suggest to adding a few drum type tutorials, for example for POP, ROCK, and others.

### 2. Edit Sound
After adding the "Load Sound" feature, I think developers must also think of other complementary features such as "Edit Sound". This feature is useful for displaying the results of an Instrumental drum record or a combination of music/song with a drum. And also users can crop, set Fade In and Fade Out, and so on. Users can also save a combined drum pattern with the "Save Project" feature.

In addition, I also recommend that you add points for the "Export to WAV" feature, this is useful for exporting project results to be managed further.

**You can see a list of features available on the "Edit Sound" page in the Component Points above.**

![1.png](https://cdn.steemitimages.com/DQmWftXXzg6RxXTGcb3JZdET53Z3mTnmox21wJvEkFJDaym/1.png)

### Mockups / Examples
Below I will show examples of locations or illustrations if the features I recommend are implemented by the Developer.

![3.png](https://cdn.steemitimages.com/DQmRZv7NpHivFTdyvygZ1vtFuhR9KTf4PEuZd7veg5qyoVD/3.png)

![4.png](https://cdn.steemitimages.com/DQmaguecTf8YFDVVxqLzNgXGttnzVW6D1yqC3JscbTL3yav/4.png)

![5.png](https://cdn.steemitimages.com/DQmdU9zc7Sse1oK51aESdYPDhbrTuzXwdXCZN7oQN2VXvAp/5.png)

![6.png](https://cdn.steemitimages.com/DQmZ81RVD7pUdBbF38v1rqy9CLcoaBsNDcnU3pzXw511MpS/6.png)

---

![7.png](https://cdn.steemitimages.com/DQmTrYkGa73jd68V3Dx8FH8CvizmfhXdTgPGw2sRNuR3BwK/7.png)

![8.png](https://cdn.steemitimages.com/DQmVTwwYEYf9zLLoH7Y6y9CkUxY3Y54Yshxf9reJeyKiSJu/8.png)

![1.png](https://cdn.steemitimages.com/DQmWftXXzg6RxXTGcb3JZdET53Z3mTnmox21wJvEkFJDaym/1.png)

### Benefits 
The benefits of the features above are as follows:
#### 1. Load Sound
- With the "Load Sound" feature, users can add music/songs to the Intrumental Drum. Users can combine Drum beats with Music/Songs to produce a synchronous beat tempo. That way, later it will produce cool Instrumental. Besides that, it will also enhance the user experience in using Drum On !.
- And with the addition of the "Lessons" feature on the "Load Sound" page, users can find tutorials/lessons for examples of drum beats or drum patterns. This will certainly be an inspiration for users to create interesting instrumentals by users.

#### 2. Edit Sound
- With the "Edit Sound" feature, users can edit the instrumental drum recordings. Like doing Crop, setting Fade In or Fade Out and others. 
- Not only for Instrumental Drum editing, if the developer applies both features that I recommend "Load Sound and Edit Sound", users can also edit music / songs that are on combined with the drum beat of Drum On !.
- Besides being able to save the edits of the drum beat pattern using the "save project" feature, users can also take advantage of the "Export To WAV" feature on the "Edit Sound" page to export the results of the instrumental project.

![1.png](https://cdn.steemitimages.com/DQmWftXXzg6RxXTGcb3JZdET53Z3mTnmox21wJvEkFJDaym/1.png)

### Conclusion
To implement the above features, the developer may need to make major improvements. And in my opinion, it won't matter because it will have a good effect later.

The features that I recommend are certainly very useful for users and developers. And this will add value to the Drum On!. And I hope, Drum On! developers will soon be able to implement this suggestion.

**Comment by tube42** [comment]
I think you are missing an important issue here:

The save screen (see your "original look", right picture) is meant to be used for live playing, thats why it looks like a drumpad. You are removing the apps main function to add something that it is not really supposed to do.
