### ISSUE TITLE
Big Thanks! And Little Feature Requests

### ISSUE THREAD

**Issue by amo13** [tube42/drumon#2]
Hey it is amazing that you made this app! Actually it is the first FOSS Drum Sequencer and therefore it's also the only one available on F-Droid! Thanks a lot, since I don't use the google apps and the play store. And I will probably be using it on a regular basis! Very nice design and animations btw =)

Here some suggestions for improvements:
- landscape view (horizontal) for tablet use
- double the amount of steps (allows a lot more grooves)
- long press on delete/reset button resets all eight sequences
- go back to normal sequencer view after BPM selection (on releasing the slider)
- Import own sample packs (would be enough to have 9 banks for each sample)

When in landscape view, the screen easily allows for the double amount of steps to be displayed. The instrument/sample selection buttons could be at the bottom right on the screen and the eight settings button on the button left of the screen. 
As for changing switching between portrait and landscape view maybe following suggestion: portrait view always has 16 steps and loops these, while landscape view always displays 32 steps. If switching from landscape to portrait, just ignore the steps 17 to 32 and loop only the first 16, as there is no space to display more. If starting in portrait view and switching to landscape view, steps 17 to 32 will be empty while there may already be a nice loop in place for the first 16 steps. In that case (second half empty on switching view), just duplicate to loop from the first half onto the second half. 
Another Idea would be to have 32 steps also in portrait view: Place a second block of 16 under the first one and have the Instrument/Sample selection buttons arranged vertically at the right border of the screen, while the settings buttons can be on the left side of the screen.

Let me know what you think!

A little bug:
- When pressing multiple steps at the same time, they won't turn on. You need to press the steps one after another.

**Comment by tube42** [comment]
glad you liked it!
- landscape view (horizontal) for tablet use: the downside of all animation is that something like this at this late stage would require a lot of work, but I will look into it
- double the amount of steps (allows a lot more grooves): not sure the screen real-estate allows this, but let me look into this some more
- long press on delete/reset button resets all eight sequences: great idea, assuming libgdx supports longress this should be an easy fix to add.
- go back to normal sequencer view after BPM selection (on releasing the slider): but what if you don't get the tempo right on your first attempt? wouldnt that be very annoying?
- Import own sample packs (would be enough to have 9 banks for each sample): this would create save files that cannot be shared with other people ... but let me think about it some more.
- When pressing multiple steps at the same time, they won't turn on. You need to press the steps one after another: nope, no multi touch support but it might be an easy fix...

**Comment by amo13** [comment]
Hey, very cool if you can look into the stuff that is quickly fixed! 

Yeah multi touch support would be good! It seems to me that it's some kind of standard expectation to apps now since almost every device supports multi touch for awhile now.

You're right about the BPM selection. Maybe an automatic switch back to sequencer can happen after one or two seconds to give enough correction time if needed, but still providing the comfort of automatic switchback? A little opacity or something like that could indicate to the user that it's going to switch back in a second, and I guess if a correction is needed it would not take more than a second to get the finger back onto the slider.

Thanks again for this already amazing app!

**Comment by tube42** [comment]
- landscape view: d1aa222
- double the amount of steps: e2b0e33  
- long press: a97889a
- go back to normal sequencer view after BPM selection: wont fix
- Import own sample packs: wont fix?
- multitouch: a97889a

a97889a breaks A/B patterns, so no A/B for now.

**Comment by amo13** [comment]
Hey wow I see you are doing really nice work! Very appreciated, thanks!

**Comment by tube42** [comment]
:)
