### ISSUE TITLE
No credits in app

### ISSUE THREAD

**Issue by guysoft** [tube42/drumon#20]
There is no about or credit that you wrote this cool app dude!
You should totally include it.

**Comment by tube42** [comment]
Oh, this is important ;)

Between f-droid, android sdk, gradle, libgdx and openjdk right now nothing works (welcome to the fun world of android development) but as soon as they start working again I will add this :)

**Comment by guysoft** [comment]
Perhaps you should use something like docker or an equivalent to maintain a working build environment. I do that for kivy projects

**Comment by tube42** [comment]
If you have a docker image that matches available tool/SDK versions on fdroid _and_ Travis CI I would love to use it!

**Comment by guysoft** [comment]
Do you know what tool/SDK versions frdoid use?
They are using docker to maintain their own builder:
https://github.com/f-droid/fdroidserver

I am willing to take a look and add Trevis on top of that image if it helps

**Comment by tube42** [comment]
I am still not sure why there is a docker configuration and a vagrant configuration and why the two differ.

Anyway, commit 6ecba72 adds the about page which will be included in release 0.3.1 assuming it passes fdroid build server :)

Close this issue when you are satisfied.

**Comment by guysoft** [comment]
I have version 0.3.1, still can't see a link to this git repo or anything that would let people find where the app is. I see there is an about page using the ``?`` button.

**Comment by tube42** [comment]
No there is no link to github,

I assume if you got this via f-droid you know where to find me.

**Comment by tube42** [comment]
Added link to github page in v0.3.2
