### ISSUE TITLE
Start-from-the-beginning feature

### ISSUE THREAD

**Issue by catprisbrey** [tube42/drumon#21]
First off, GREAT app! It's been a game changer and its helpfulness is beyond words.

There is one feature that I think could be useful maybe even as a long press option for the current "Play" button. I'd like to choose whether hitting play button continues the drum pattern where it left, or to start the pattern anew from the top.

A use case example. I frequently play guitar along with the drum patterns I plug in. At some points int he song, I stop the pattern and play a bit solo and start the drum pattern back up again. But when I unpause, the pattern picks up where it left off, rather than starting the drum pattern fresh from the beginning again. I can understand both options being useful. Would this be a difficult feature to add?

**Comment by tube42** [comment]
This was added in commit 05539a5b, I just haven't had time to test it properly and do a release for F-droid.

It might take a while before I have time to do that, given the current state of things.

**Comment by tube42** [comment]
This is now configurable in v0.3.2
