### ISSUE TITLE
Contrast issue : hard to guess a muted tick

### ISSUE THREAD

**Issue by luffah** [tube42/drumon#24]
Hello,

i was searching for Hydrogen on F-Droid and i found your application which is really really nice.

The only issue i encountered is the following : the color of the current tick is not enough contrasted for me and it was hard to guess the beat on muted ticks.

_Off topic Note : On Hydrogen (or Audacity), this issue is solved with a cursor (or a line) that precisely indicate time position._

**Comment by tube42** [comment]
The colors were more or less randomly generated and do not always work well.

What color would you prefer on the marker? Keep in mind that the page changes color depending on the current instrument.

**Comment by luffah** [comment]
Using a color of existing buttons could be a simple way to preserve your design.


First i though of using the selected instrument color (line 2), but there is a contrast issue with played note.
Then i looked on the non-selected instrument color (line 3 - framed) that still more readable than red, but the contrast is not as readable using the selected instrument color on muted.
I though then to mix colors : non-selected color for played not and selected color for muted,
but the contrast on the played note would be a little sad. 
To maximize contrast, i propose to use background color for the marker on the played note (line 1 - framed).

 _Frames represent solutions proposed. First frame : maybe best but require coding; Second frame : acceptable_
![drum_on_app_design](https://user-images.githubusercontent.com/9461518/86542807-5c30a180-bf19-11ea-813f-76157ba60c62.png)

**Comment by tube42** [comment]
Note that the marker is moving (and changes size slightly). Using the background color will make it disappear while moving between the notes.

There is also the complication of pads and background changing color for each instrument. Maybe we should start by either improving or removing that first. Once that looks acceptable it should be easier to find a solution to this.

**Comment by luffah** [comment]
On the version i have, i just see the marker bouncing. No translation move between note.

**Comment by tube42** [comment]
Hmm... that is not right.

For starters, commit 1b3b36a9b74fbd3448e03a616814fd7eaec530fd changes marker behavior so it moves more in sync with the tempo. I also updates pad and background colors to make it more visible.

If you have the ability to build from source, try it out and tell me what you think.

**Comment by luffah** [comment]
The new version is visually more clear on this point.

Too bad it (the new background) breaks the design a bit.

The addition to show instrument could be more intuitive (e.g. using additionnal icon for each instrument, a stick for stick.. a cowbell for cowbell...) but it still fast to guess the behaviour.

Issue solved anyway ^^.

**Comment by tube42** [comment]
Better instruments icon would be really nice, they would make things more innovative and remove the need for the ugly indicator that was added in v0.3.3

But I am good enough of an artist to draw those icons...
