### ISSUE TITLE
[feature-request] Add a shaker sound

### ISSUE THREAD

**Issue by Sogolumbo** [tube42/drumon#25]
I'd love to have a shaker sound added. 
For me placement on the clap icon would make sense.

**Comment by tube42** [comment]
Can you point me to a good shaker sound you are happy with?

**Comment by Sogolumbo** [comment]
I don't really have any samples at hand that you could straight up add.
I'm looking for a shaker sound like in this video:
[beatbox](https://www.youtube.com/watch?v=UkgZ47YhV5w&t=5m57s)
[instrumental](https://www.youtube.com/watch?v=UkgZ47YhV5w&t=6m34s)
For a rough estimate here are some examples:
https://samplefocus.com/samples/live-perc-125-18-414cb249-6280-4391-a00f-73cc61e28f6c
https://samplefocus.com/samples/shaker-loop-95
https://samplefocus.com/samples/shaker-long-and-short
https://samplefocus.com/samples/long-shaker

**Comment by tube42** [comment]
Okay, I did a quick test and it doesn't sound good. The problem is that shaker makes two sounds (back and forth) which are tempo and style dependent.

If I only add one sample it will sound like a really crappy high-hat.

Try it yourself: https://samplefocus.com/samples/light-shaker

**Comment by Sogolumbo** [comment]
I understand that's a problem.
I have an idea to control the sound with a 2D slider:
Y-Axis: volume ratio of the main beat to every second beat.
X-Axis: timing of the second beat.
Maybe it would sound good to also control a slight low-pass filter with the y-axis to give a moremuffled sound to the quieter beat.

Edit:
I just realized that my given example has accents every fouth "shake" but the timing is changed four every second beat.
That would require a lot of controls, which would compromise the clean UI.

One more idea:
Instead of 2D controls for the timing and accents give genre presets in a drop down list.

**Comment by tube42** [comment]
Great idea, but I think the complexity is a bit too much for this app.

Version 0.3.2 should show up on f-droid soon and will include a simple shaker sound. Lets see how that works first.
