### ISSUE TITLE
New feature: ternary beat

### ISSUE THREAD

**Issue by ghost** [tube42/drumon#3]
Thanks for creating DrumOn and sharing it on FDroid! It is now my favourite metronome app :)
How about adding a ternary beat to the tempo selector? 3/4 or 6/8 would do.

Thanks in advance!

**Comment by tube42** [comment]
So basically 4/4 without the last column and 4/8 without that last two? Seems perfectly doable.

**Comment by tube42** [comment]
Added in 9acda5f  aka v0.2.2 , although I am not 100% sure if my interpretation of the ternary measures is correct.

Should show up on fdroid within 48 hours.

**Comment by ghost** [comment]
I just upgraded and tested it, it's exactly what I had in mind.
Thanks so much for the new feature!
