### ISSUE TITLE
New feature idea: Instrument Panning

### ISSUE THREAD

**Issue by catprisbrey** [tube42/drumon#30]
I'm not sure if this app is currently in stereo, but I had this thought today:

What if a long press on the instrument showed the typical box of Volume/Variation, but also a slider bar along the top of the screen for Left/Right panning. I use this app a TON (probably for an hour a day... every day.. Part of why I also want a way to send you donation money! I love this app!!!). 

Adding a slider to do some panning of the individual instruments would step up the way i use this app even more. Pushing hats right, toms left, crashes off to the side, etc. If that's not possible, then I totally understand, but if it is! That would be awesome to add!

**Comment by tube42** [comment]
Panning the drums is a good idea, but that would require re-writing all code from mono to stereo

There are two issues with stereo: doesn't sound that good on most phones anyway and its twice as computationally intensive as mono. 

Performance is an issue since my development phone is from 2012 ...

**Comment by catprisbrey** [comment]
Fair enough reason given phones will typically be used mono unless piping out speakers. Closing the ticket
