### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [tube42/drumon#33]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the button each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
App version is 0.3.3, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="474" alt="bug-drum" src="https://user-images.githubusercontent.com/18572115/103165699-faad1800-4855-11eb-9da5-56fdce034e73.png">

**Comment by tube42** [comment]
I am not sure what the problem is, hard to figure out from the image

**Comment by tube42** [comment]
No response from reporter, closed
