### ISSUE TITLE
Not in strict time

### ISSUE THREAD

**Issue by sandoxy** [tube42/drumon#34]
I tried to record my experiments with this app and a syntethizer on my computer. But it seems like this app is not in strict time. I used my separate metronome devise to confirm it.

**Comment by tube42** [comment]
Nope, can't reproduce this in any way. Tried with analog and digital metronomes and a computer.

**Comment by edgar-bonet** [comment]
Same issue here. LineageOS (Android 7.1.2) on a Samsung Galaxy J3:

* setting the tempo to 85 gives something around 86–87
* setting it to 90 gives a tempo of 130.
