### ISSUE TITLE
Include a Changelog Link, on the F-Droid Info' Page, 0.2.3.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [tube42/drumon#4]
Include a Changelog Link, on the F-Droid Info' Page.  Now on 0.2.3, which has none.

**Comment by locutis-of-borg-1999** [comment]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not Present, as of: 0.2.3.

**Comment by tube42** [comment]
The problem is that fdroid does not incorporate changelogs from git releases.

If you really want to fix this issue, modify the fdroid server code to include changelogs from git and submit it to the fdroid maintainers!

**Comment by locutis-of-borg-1999** [comment]
Unless I'm misinformed, on the F-Droid site, just as within the F-Droid app', it's simply a link.  It's just as with many projects on F-Droid that have a "donate", or Flattr link.

Although you might want a few brief summary notes of the **actual changes** on the following page, you could just refer to:  
https://github.com/tube42/drumon/releases

**Comment by locutis-of-borg-1999** [comment]
The F-Droid page for your project already includes links for "source code", "website", and "issues"/"issue tracker", all pointing to github.  
https://f-droid.org/repository/browse/?fdid=se.tube42.drum.android

It's not much of a stretch, to include a changelog.  
https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by tube42** [comment]
No, it is more than just a link. The drumon entry in fdroid database states that whenever a new git release tag is seen on github fdroid server bot should build that particular release and publish it on their site. During that process Fdroid extracts a lot of data from the drumon repository (for example it parses the manifest to check if the app permission have changed).  The **correct** way to do things would then be to also pull the release log.

Technically, I could add the release page to fdroid but (1) the release page makes a very confusing changelog, (2) making changes to fdroid database is a PITA and I would avoid it if possible and (3) the fdroid team is very busy and don't want thousands of one-line pull requests to process.

Now if you really really want this I suggest you submit a single (!) pull request that adds the release page as changelog to ALL github projects you have been contacting this week. Both the maintainers and the fdroid team will be grateful to you.
