### ISSUE TITLE
applicationID changed in 0.2.6

### ISSUE THREAD

**Issue by licaon-kter** [tube42/drumon#5]
...was that intentional?

I've [renamed it back to allow it to be build in F-Droid](https://gitlab.com/fdroid/fdroiddata/merge_requests/3476/diffs) for now, but if this is the new official ID maybe I'd need to actually add it as a new app with this new ID.

**Comment by tube42** [comment]
No, this was an error. How should I fix this? A new release with correct ID?

**Comment by licaon-kter** [comment]
Yes, it's fixed for version 0.2.6 on F-Droid, so I guess you can fix it now and for the next release it will be ok.

**Comment by tube42** [comment]
Great, thanks!

4289698b fixes this with v0.2.7.
