### ISSUE TITLE
support to add/remove lines

### ISSUE THREAD

**Issue by sleep-walker** [tube42/drumon#9]
Thanks for making this application! I use it to train my djembe playing and I put there patterns (not only) from this video:

https://youtu.be/Wqux-4IupdU?t=5m16s

I'm not musician, but I have difficulty with this example. Timestamp leads to pattern #11, which contains 3 groups of 4 notes. I'd need to be able to insert notes into 4x3 grid, but I can have only 3x4 grid with the same length (which I used for now, but it is rather confusing). One of the way how to achieve that would be add support for adding/removing lines so I'd take 4/4 and remove one line.

Could you consider such feature? Is there better way how to achieve it?

(PS: More african drum sounds, please! :)

**Comment by tube42** [comment]
If you have some free to use African drums I would be happy to add them!

Not sure about 4-4-4 beats (which probably has a more fancy name :) ). I need to have a good look at the UI code before I say anything. Last time 6/8 was a major pain to get animated correctly :(

**Comment by tube42** [comment]
@sleep-walker do you have any drum sounds you want to add?

**Comment by tube42** [comment]
I don't really know much about African drums, but I received some samples which will show up in the next version (v0.3.3 ).

**Comment by tube42** [comment]
3-x-x grids was added in f8ae529f08987f68eb76d20c048ebbe620ae0930 and should land in v0.3.4.
